dataset: imagenet
num_classes: 1000
img_size: 224
mean:
    - 0.485
    - 0.456
    - 0.406
std:
    - 0.229
    - 0.224
    - 0.225
crop_pct: 0.875
color_jitter: 0
scale:
    - 0.08
    - 1.0
interpolation: bicubic
train_interpolation: random
# aa: rand-m9-mstd0.5-inc1
mixup: 0.0
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_mode: batch
mixup_switch_prob: 0.5
cutmix: 0.0
reprob: 0.25
remode: pixel
amp: True
model_ema: False
batch_size: 512
lr: 75e-5
min_lr: 1e-5
model: mobilenetv2_100
log_interval: 100
# pretrained: True
sched: cosine
weight_decay: 3e-2
epochs: 150
cooldown_epochs: 10
warmup_epochs: 5
warmup_lr: 0.00001
opt: adamw
smoothing: 0.1
workers: 8
wq_enable: False
wq_mode: "TWN"
wq_bitw: 1
wq_asym: False
aq_enable: False
aq_mode: "LSQ"
aq_bitw: 1
resq_enable: False
resq_mode: "LSQ"
resq_bitw: 1
wq_per_channel: True
qmodules: 
  - "blocks.0.0.conv_pw"
  - "blocks.0.0.conv_dw;wq:bit:1"
  - "blocks.1.0.conv_pw"
  - "blocks.1.0.conv_dw;wq:bit:1"
  - "blocks.1.0.conv_pwl"
  - "blocks.1.1.conv_pw"
  - "blocks.1.1.conv_dw;wq:bit:1"
  - "blocks.1.1.conv_pwl"
  - "blocks.2.0.conv_pw"
  - "blocks.2.0.conv_dw;wq:bit:1"
  - "blocks.2.0.conv_pwl"
  - "blocks.2.1.conv_pw"
  - "blocks.2.1.conv_dw;wq:bit:1"
  - "blocks.2.1.conv_pwl"
  - "blocks.2.2.conv_pw"
  - "blocks.2.2.conv_dw;wq:bit:1"
  - "blocks.2.2.conv_pwl"
  - "blocks.3.0.conv_pw"
  - "blocks.3.0.conv_dw;wq:bit:1"
  - "blocks.3.0.conv_pwl"
  - "blocks.3.1.conv_pw"
  - "blocks.3.1.conv_dw;wq:bit:1"
  - "blocks.3.1.conv_pwl"
  - "blocks.3.2.conv_pw"
  - "blocks.3.2.conv_dw;wq:bit:1"
  - "blocks.3.2.conv_pwl"
  - "blocks.3.3.conv_pw"
  - "blocks.3.3.conv_dw;wq:bit:1"
  - "blocks.3.3.conv_pwl"
  - "blocks.4.0.conv_pw"
  - "blocks.4.0.conv_dw;wq:bit:1"
  - "blocks.4.0.conv_pwl"
  - "blocks.4.1.conv_pw"
  - "blocks.4.1.conv_dw;wq:bit:1"
  - "blocks.4.1.conv_pwl"
  - "blocks.4.2.conv_pw"
  - "blocks.4.2.conv_dw;wq:bit:1"
  - "blocks.4.2.conv_pwl"
  - "blocks.5.0.conv_pw"
  - "blocks.5.0.conv_dw;wq:bit:1"
  - "blocks.5.0.conv_pwl"
  - "blocks.5.1.conv_pw"
  - "blocks.5.1.conv_dw;wq:bit:1"
  - "blocks.5.1.conv_pwl"
  - "blocks.5.2.conv_pw"
  - "blocks.5.2.conv_dw;wq:bit:1"
  - "blocks.5.2.conv_pwl"
  - "blocks.6.0.conv_pw"
  - "blocks.6.0.conv_dw;wq:bit:1"
  - "blocks.6.0.conv_pwl"
  - "conv_head"
